name: MultiChat
version: "1.10"
author: Revilo410
api-version: 1.13
main: xyz.olivermartin.multichat.local.spigot.MultiChatLocalSpigotPlugin
softdepend: [Vault,PlaceholderAPI]
commands:
   nick:
      description: Gives a player a nickname
      usage: /nick [player] <nickname / off>
      permission: multichatlocal.nick.self
      permission-message: You do not have permission (multichatlocal.nick.self / multichatlocal.nick.others)
   realname:
      description: Gets the real name of a player from a nickname
      usage: /realname <nickname>
      permission: multichatlocal.realname
      permission-message: You do not have permission (multichatlocal.realname)
   username:
      description: Searches for a user with the specified name
      usage: /username <query>
      permission: multichatlocal.username
      permission-message: You do not have permission (multichatlocal.username)
   multichatlocal:
      description: MultiChatLocal reload, debug and migrate commands
      usage: /multichatlocal [reload/debug/migratetosql]
      permission: multichatlocal.reload
      permission-message: You do not have permission (multichatlocal.reload)
   pxe:
      description: Proxy Execute - Execute commands on Proxy server
      usage: /pxe [-p <player>] <command to execute>
      permission: multichatlocal.pexecute
      permission-message: You do not have permission (multichatlocal.pexecute)
   pexecute:
      description: Proxy Execute - Execute commands on Proxy server
      usage: /pexecute [-p <player>] <command to execute>
      permission: multichatlocal.pexecute
      permission-message: You do not have permission (multichatlocal.pexecute)
      