############################################################
# +------------------------------------------------------+ #
# |                   MultiChatSpigot                    | #
# +------------------------------------------------------+ #
############################################################

# By Revilo410

##################
# NE PAS EDITER  #
version: "1.7.3" #
##################


# French Translation by Nogapra - Thank you !
# Pour utiliser ce fichier, renommer en 'spigotconfig.yml'.

#1. Global
#2. Local
#3. Placeholders MultiChat
#4. Surnom MultiChat

############################################################
# +------------------------------------------------------+ #
# |                        Global                        | #
# +------------------------------------------------------+ #
############################################################

# Définie si ce serveur utilise un format différent pour le chat global que celui attribué
# dans le dossier plugins du serveur BungeeCoord ?
# (Utile si vous souhaitez utiliser des Placeholders locaux qui ne peuvent être présents que sur un seul serveur).
# Paramètre disponible : true ou false
override_global_format: false

# Format à utiliser pour le chat global si le paramètre ci-dessus est défini sur true.
# 
# Utiliser les codes couleur Minecraft standard '&X' COLOUR/FORMAT CODES.
# %NAME% = Le nom de l’expéditeur.
# %DISPLAYNAME% = Le nom d'affichage de l’expéditeur.
# %PREFIX% = Le préfixe de l’expéditeur.
# %SUFFIX% = Le suffixe de l’expéditeur.
# %NICK% = Le surnom de l’expéditeur.
# %SERVER% = Le serveur de l’expéditeur.
# %WORLD% = Le monde de l’expéditeur.
#
# S’affichera en tant que [FORMAT] [MESSAGE]
override_global_format_format: "&5[&dG&5] &f%DISPLAYNAME%&f: "

# Si le paramètre ci-dessous est défini sur true, alors quels que soient les paramètres ci-dessus, 
# MultiChat ne touchera pas le format de chat.
# Cela signifie que si un plugin tel que Towny gère le format de chat localement, alors ce sera utilisé à la place.
# MultiChat enverra toujours le message à tous les autres serveurs.
# 
# NOTE : CECI EST FAIT SUR UNE BASE DU MEILLEUR EFFORT !
#(MultiChat est un plugin de formatage de chat est donc conçu pour formater le chat!)
# Paramètre disponible : true ou false
override_all_multichat_formatting: false

# Définir ce paramètre sur true essaiera de prendre le contrôle malgré un plugin de formatage de chat récalcitrant.
# Paramètre disponible : true ou false
force_multichat_format: false


############################################################
# +------------------------------------------------------+ #
# |                        Local                         | #
# +------------------------------------------------------+ #
############################################################

# MultiChat doit-il définir le format du chat local ? (Laisser cela à false permet à d’autres plugins de gérer le chat)
# Paramètre disponible : true ou false
set_local_format: true

#Utiliser les codes couleur Minecraft standard '&X' COLOUR/FORMAT CODES.
# %NAME% = Le nom de l’expéditeur.
# %DISPLAYNAME% = Le nom d'affichage de l’expéditeur.
# %PREFIX% = Le préfixe de l’expéditeur.
# %SUFFIX% = Le suffixe de l’expéditeur.
# %NICK% = Le surnom de l’expéditeur.
# %SERVER% = Le serveur de l’expéditeur.
# %WORLD% = Le monde de l’expéditeur.
#
# S’affichera en tant que [FORMAT] [MESSAGE]
local_chat_format: "&3[&bL&3] &f%DISPLAYNAME%&f: &7"

############################################################
# +------------------------------------------------------+ #
# |                 Placeholders MultiChat               | #
# +------------------------------------------------------+ #
############################################################

# Ce paramètre vous permet d’utiliser des variables discussion dans d’autres plugins!
# Par exemple, si vous utilisez le chat Essentials pour votre chat local, mais que vous vouliez utiliser un Pseudo de multichat.
# Vous pouvez spécifier le PlaceHolder {multichat_nickname} comme défini ci-dessous. MultiChat l’analysera comme d’habitude.
# Essentials ne prend pas en charge l’API de Placeholder par défaut,
# mais vous pouvez toujours utiliser les PlaceHolder PAPI en en paramétrant un ci-dessous!
# {multichat_papi_displayname} will be replaced using the example below and parsed by multichat.
multichat_placeholders:
  nickname: "%NICK%"
  papi_displayname: "%player_displayname%"

############################################################
# +------------------------------------------------------+ #
# |                   Surnom MultiChat                   | #
# +------------------------------------------------------+ #
############################################################

# Les joueurs ne pourront se renommer avec un surnom de cette liste !
# (?i) est le regex pour ignorer le cas.
nickname_blacklist:
- "(?i)Notch"
- "(?i)Jeb"
#- "[1234567890]+.*" # <-- Exemple pour bloquer les surnoms commençant par un nombre !

# Un préfixe doit-il être affiché avant les surnoms pour les différencier des vrais noms ?
# Paramètre disponible : true ou false
show_nickname_prefix: false

# Que doit être affiché avant le surnom ?
nickname_prefix: "~"
